name: 🚀 Nuxt

on:
  push:
    branches: ['prod']

jobs:
  # Checkout, Setup and Install Dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Node.js Dependencies
        run: npm install

  # Nuxt post-install actions
  postinstall:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Post-install Actions
        run: npm run postinstall

  # Prettier
  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Prettier
        run: npm run check

  # ESLint
  lint:
    runs-on: ubuntu-latest
    needs: postinstall
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Lint
        run: npm run postinstall && npm run lint

  # Types check
  typeslint:
    runs-on: ubuntu-latest
    needs: postinstall
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Typeslint
        run: npm run postinstall && npm run typeslint

  # Stylelint
  stylelint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Stylelint
        run: npm run slint

  # Build Assets & Pre-render from nuxt.config.ts
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Build Assets with pre-render
        run: npm run build

  # Run Vitests
  test:
    runs-on: ubuntu-latest
    needs: postinstall
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Node.js Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Execute tests via Vitest
        run: npm run postinstall && npm run test:coverage
