export const SET_ITEMS_PER_PAGE: string = 'SET_ITEMS_PER_PAGE'
export const SET_CURRENT_PAGE: string = 'SET_CURRENT_PAGE'
export const SET_TOTAL_PAGES: string = 'SET_TOTAL_PAGES'
export const SET_ERROR: string = 'SET_ERROR'
export const SET_LOADING: string = 'SET_LOADING'
export const SET_TAGS: string = 'SET_TAGS'
