#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/pest
npm run lint
npm run build
npm run write

if [ -n "$(git status --porcelain)" ]; then
  # Commit all modified files
  git add .
fi
